image:
    repository: 870140859713.dkr.ecr.us-east-1.amazonaws.com/hw-ecr
    tag: v1.0.3
    pullPolicy: Always

service:
    type: ClusterIP
    port: 8000

ingress:
    enabled: false

config:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
    POSTGRES_USER: django_user
    POSTGRES_DB: django_db
    POSTGRES_PASSWORD: pass9764gd
